import type { Prospect } from "./types";

/**
 * Données 100 % fictives — sociétés, numéros BCE, personnes et emails inventés.
 * Échantillon volontairement mixte : chemins heureux + cas limites
 * (score sous le seuil, pas de données Pappers, pas de LinkedIn, timeout API).
 */
export const PROSPECTS: Prospect[] = [
  {
    id: "p01",
    name: "Fonderie Delcourt SA",
    enterpriseNumber: "0412.887.301",
    city: "Charleroi",
    province: "Hainaut",
    workerBand: "50-99",
    sector: "Métallurgie",
    scenario: "ok",
    healthScore: 74,
    healthBand: "Solide",
    whyCallNow:
      "Vient d'annoncer l'extension de son site de Marchienne (+30 postes de production) — un pic d'embauche sans équipe RH élargie.",
    signals: [
      { date: "28 juil. 2026", title: "Extension du site de Marchienne annoncée : +30 recrutements de production d'ici décembre", source: "L'Echo" },
      { date: "9 juil. 2026", title: "Publication de 6 offres (opérateurs CNC, chef d'équipe) sur son site carrières", source: "Site web" },
      { date: "12 juin 2026", title: "Nomination d'un nouveau directeur des opérations, ex-Aperam", source: "LinkedIn" },
    ],
    contacts: [
      { name: "Marc Delcourt", role: "Administrateur délégué", roleGroup: "CEO", email: "m.delcourt@fonderie-delcourt.example" },
      { name: "Sophie Lambrechts", role: "Responsable comptabilité", roleGroup: "Comptabilité", email: "s.lambrechts@fonderie-delcourt.example" },
      { name: "Yasmina El Fassi", role: "Gestionnaire paie", roleGroup: "Payroll", email: "y.elfassi@fonderie-delcourt.example" },
      { name: "Julien Warnier", role: "HR Officer", roleGroup: "RH", email: "j.warnier@fonderie-delcourt.example" },
    ],
    otherContactsCount: 43,
  },
  {
    id: "p02",
    name: "TransWal Logistics",
    enterpriseNumber: "0466.120.554",
    city: "Liège",
    province: "Liège",
    workerBand: "100-199",
    sector: "Transport & logistique",
    scenario: "ok",
    healthScore: 81,
    healthBand: "Solide",
    whyCallNow:
      "Nouveau hub de 12 000 m² aux Hauts-Sarts opérationnel en septembre — la paie de ±40 intérimaires passera en interne selon leur CFO.",
    signals: [
      { date: "24 juil. 2026", title: "Ouverture confirmée du hub Hauts-Sarts : 12 000 m², ±40 postes logistiques", source: "La Libre Eco" },
      { date: "2 juil. 2026", title: "Le CFO évoque l'internalisation de la gestion de paie dans une interview", source: "Trends-Tendances" },
      { date: "18 juin 2026", title: "Campagne de recrutement caristes/dispatchers sur les réseaux", source: "LinkedIn" },
    ],
    contacts: [
      { name: "Olivier Bastin", role: "CEO", roleGroup: "CEO", email: "o.bastin@transwal.example" },
      { name: "Carine Dupuis", role: "Comptable senior", roleGroup: "Comptabilité", email: "c.dupuis@transwal.example" },
      { name: "Peter Vandenbroeck", role: "Payroll Manager", roleGroup: "Payroll", email: "p.vandenbroeck@transwal.example" },
      { name: "Awa Diallo", role: "HR Business Partner", roleGroup: "RH", email: "a.diallo@transwal.example" },
    ],
    otherContactsCount: 87,
  },
  {
    id: "p03",
    name: "CleanBureau Services SRL",
    enterpriseNumber: "0533.409.118",
    city: "Bruxelles",
    province: "Bruxelles-Capitale",
    workerBand: "20-49",
    sector: "Nettoyage",
    scenario: "below_threshold",
    healthScore: 32,
    healthBand: "À risque",
    whyCallNow: "",
    signals: [],
    contacts: [],
    otherContactsCount: 0,
  },
  {
    id: "p04",
    name: "Menuiserie Hautecoeur & Fils",
    enterpriseNumber: "0479.882.647",
    city: "Verviers",
    province: "Liège",
    workerBand: "10-19",
    sector: "Construction — bois",
    scenario: "no_pappers",
    healthScore: null,
    healthBand: "Inconnue",
    whyCallNow:
      "Recrute 3 menuisiers-poseurs depuis mai sans succès visible — les offres sont republiées toutes les 3 semaines.",
    signals: [
      { date: "21 juil. 2026", title: "Republication des 3 offres de menuisier-poseur (3e cycle depuis mai)", source: "Site web" },
      { date: "30 mai 2026", title: "Premier cycle d'offres menuisiers-poseurs publié", source: "Site web" },
    ],
    contacts: [
      { name: "Bernard Hautecoeur", role: "Gérant", roleGroup: "CEO", email: "b.hautecoeur@hautecoeur.example" },
      { name: "Martine Collard", role: "Comptable externe", roleGroup: "Comptabilité", email: "m.collard@fidu-collard.example" },
    ],
    otherContactsCount: 4,
  },
  {
    id: "p05",
    name: "InfraGreen Wallonie SA",
    enterpriseNumber: "0691.233.905",
    city: "Mons",
    province: "Hainaut",
    workerBand: "50-99",
    sector: "Énergie & environnement",
    scenario: "ok",
    healthScore: 77,
    healthBand: "Solide",
    whyCallNow:
      "Marché public de 14 M€ remporté en juin (éclairage LED provincial) — montée en charge chantiers dès la rentrée.",
    signals: [
      { date: "17 juil. 2026", title: "Attribution confirmée du marché LED provincial (14 M€, 3 ans)", source: "Le Soir" },
      { date: "5 juil. 2026", title: "5 offres publiées : électriciens industriels, 2 chefs de chantier", source: "Site web" },
      { date: "11 juin 2026", title: "Levée de fonds growth de 4 M€ auprès de W.IN.G", source: "Trends-Tendances" },
    ],
    contacts: [
      { name: "Isabelle Marchal", role: "CEO", roleGroup: "CEO", email: "i.marchal@infragreen.example" },
      { name: "Thomas Petit", role: "Responsable finance", roleGroup: "Comptabilité", email: "t.petit@infragreen.example" },
      { name: "Nadia Bouziane", role: "HR & Payroll Officer", roleGroup: "Payroll", email: "n.bouziane@infragreen.example" },
      { name: "Céline Devos", role: "Talent Acquisition Lead", roleGroup: "RH", email: "c.devos@infragreen.example" },
    ],
    otherContactsCount: 31,
  },
  {
    id: "p06",
    name: "Boulangeries Pain d'Antan",
    enterpriseNumber: "0508.771.240",
    city: "Tournai",
    province: "Hainaut",
    workerBand: "20-49",
    sector: "Alimentaire",
    scenario: "no_linkedin",
    healthScore: 69,
    healthBand: "Solide",
    whyCallNow:
      "Ouvre son 4e atelier (Mouscron) en octobre — recrutements boulangers et vendeuses en cours, aucune structure RH interne.",
    signals: [
      { date: "26 juil. 2026", title: "Annonce de l'ouverture du 4e atelier à Mouscron (octobre)", source: "L'Avenir" },
      { date: "10 juil. 2026", title: "4 offres en vitrine et sur le site : 2 boulangers, 2 vendeuses", source: "Site web" },
    ],
    contacts: [],
    otherContactsCount: 0,
  },
  {
    id: "p07",
    name: "SoftBridge Consulting",
    enterpriseNumber: "0645.998.312",
    city: "Louvain-la-Neuve",
    province: "Brabant wallon",
    workerBand: "20-49",
    sector: "IT & conseil",
    scenario: "api_error",
    healthScore: null,
    healthBand: "Inconnue",
    whyCallNow: "",
    signals: [],
    contacts: [],
    otherContactsCount: 0,
  },
  {
    id: "p08",
    name: "Transports Bodart & Cie",
    enterpriseNumber: "0421.336.870",
    city: "Arlon",
    province: "Luxembourg",
    workerBand: "50-99",
    sector: "Transport & logistique",
    scenario: "ok",
    healthScore: 71,
    healthBand: "Solide",
    whyCallNow:
      "Reprise de la flotte de Muller Trans (11 chauffeurs à intégrer au 1er septembre) — harmonisation des barèmes à gérer.",
    signals: [
      { date: "22 juil. 2026", title: "Rachat de la flotte Muller Trans finalisé : 11 chauffeurs repris", source: "L'Avenir Luxembourg" },
      { date: "8 juil. 2026", title: "Offre publiée : gestionnaire administratif transport", source: "Site web" },
      { date: "19 juin 2026", title: "Extension du dépôt de Weyler autorisée (permis accordé)", source: "Le Soir" },
    ],
    contacts: [
      { name: "François Bodart", role: "Administrateur délégué", roleGroup: "CEO", email: "f.bodart@bodart-cie.example" },
      { name: "Anne-Sophie Gérard", role: "Responsable comptabilité", roleGroup: "Comptabilité", email: "as.gerard@bodart-cie.example" },
      { name: "Luc Thiry", role: "Gestionnaire paie & flotte", roleGroup: "Payroll", email: "l.thiry@bodart-cie.example" },
    ],
    otherContactsCount: 19,
  },
  {
    id: "p09",
    name: "Chocolaterie Werrens NV",
    enterpriseNumber: "0456.220.983",
    city: "Gand",
    province: "Flandre-Orientale",
    workerBand: "50-99",
    sector: "Alimentaire",
    scenario: "ok",
    healthScore: 66,
    healthBand: "Solide",
    whyCallNow:
      "Double sa capacité export US après un contrat retail signé en juin — équipe production passera en 2×8 dès novembre.",
    signals: [
      { date: "29 juil. 2026", title: "Contrat retail US signé : la production passera en 2 équipes dès novembre", source: "De Tijd" },
      { date: "14 juil. 2026", title: "6 offres : opérateurs de production, 1 team leader, 1 qualité", source: "Site web" },
      { date: "23 juin 2026", title: "Investissement de 2,1 M€ dans une nouvelle ligne d'enrobage", source: "Made in Oost-Vlaanderen" },
    ],
    contacts: [
      { name: "Karel Werrens", role: "CEO", roleGroup: "CEO", email: "k.werrens@werrens.example" },
      { name: "Els De Smet", role: "Hoofd boekhouding", roleGroup: "Comptabilité", email: "e.desmet@werrens.example" },
      { name: "Inge Vermeulen", role: "Payroll specialist", roleGroup: "Payroll", email: "i.vermeulen@werrens.example" },
      { name: "Dries Callens", role: "HR-verantwoordelijke", roleGroup: "RH", email: "d.callens@werrens.example" },
    ],
    otherContactsCount: 52,
  },
  {
    id: "p10",
    name: "Ateliers Maréchal SA",
    enterpriseNumber: "0402.115.669",
    city: "Namur",
    province: "Namur",
    workerBand: "20-49",
    sector: "Maintenance industrielle",
    scenario: "ok",
    healthScore: 58,
    healthBand: "Solide",
    whyCallNow:
      "Contrat de maintenance pluriannuel signé avec un acteur pharma de Gosselies — 8 techniciens à recruter avant fin d'année.",
    signals: [
      { date: "25 juil. 2026", title: "Contrat de maintenance 5 ans signé (site pharma, Gosselies)", source: "L'Echo" },
      { date: "16 juil. 2026", title: "8 offres de techniciens de maintenance publiées d'un coup", source: "Site web" },
    ],
    contacts: [
      { name: "Vincent Maréchal", role: "Administrateur délégué", roleGroup: "CEO", email: "v.marechal@ateliers-marechal.example" },
      { name: "Chantal Focan", role: "Comptable", roleGroup: "Comptabilité", email: "c.focan@ateliers-marechal.example" },
      { name: "Rachid Benali", role: "HR Generalist", roleGroup: "RH", email: "r.benali@ateliers-marechal.example" },
    ],
    otherContactsCount: 12,
  },
  {
    id: "p11",
    name: "Clinique Vétérinaire des Étangs",
    enterpriseNumber: "0562.874.401",
    city: "Wavre",
    province: "Brabant wallon",
    workerBand: "10-19",
    sector: "Santé animale",
    scenario: "ok",
    healthScore: 55,
    healthBand: "Solide",
    whyCallNow:
      "Fusion avec le cabinet de Rixensart au 1er octobre — passage de 12 à 21 salariés, deux régimes de paie à unifier.",
    signals: [
      { date: "27 juil. 2026", title: "Fusion annoncée avec le cabinet vétérinaire de Rixensart (effectif : 12 → 21)", source: "L'Avenir BW" },
      { date: "3 juil. 2026", title: "2 offres : assistant(e) vétérinaire, secrétaire médicale", source: "Site web" },
    ],
    contacts: [
      { name: "Dr Hélène Rousseau", role: "Associée gérante", roleGroup: "CEO", email: "h.rousseau@vet-etangs.example" },
      { name: "Fabienne Docquier", role: "Secrétariat & comptabilité", roleGroup: "Comptabilité", email: "f.docquier@vet-etangs.example" },
    ],
    otherContactsCount: 7,
  },
  {
    id: "p12",
    name: "Brasserie du Perron SRL",
    enterpriseNumber: "0437.590.226",
    city: "Huy",
    province: "Liège",
    workerBand: "10-19",
    sector: "Brasserie",
    scenario: "ok",
    healthScore: 63,
    healthBand: "Solide",
    whyCallNow:
      "Nouvelle ligne d'embouteillage livrée en août + saison des fêtes — recours massif aux flexi-jobs en préparation.",
    signals: [
      { date: "30 juil. 2026", title: "Réception de la nouvelle ligne d'embouteillage (capacité ×2)", source: "La Meuse" },
      { date: "12 juil. 2026", title: "Appel à flexi-jobs pour la saison automne-fêtes sur ses réseaux", source: "Facebook" },
    ],
    contacts: [
      { name: "Grégory Lhoest", role: "Fondateur & gérant", roleGroup: "CEO", email: "g.lhoest@brasserieduperron.example" },
      { name: "Aurélie Mathieu", role: "Office manager (compta & paie)", roleGroup: "Comptabilité", email: "a.mathieu@brasserieduperron.example" },
    ],
    otherContactsCount: 5,
  },
  {
    id: "p13",
    name: "Securitex Gardiennage SA",
    enterpriseNumber: "0498.336.107",
    city: "Anvers",
    province: "Anvers",
    workerBand: "200-499",
    sector: "Sécurité",
    scenario: "below_threshold",
    healthScore: 41,
    healthBand: "À risque",
    whyCallNow: "",
    signals: [],
    contacts: [],
    otherContactsCount: 0,
  },
  {
    id: "p14",
    name: "Pépinières Van Damme BV",
    enterpriseNumber: "0471.605.883",
    city: "Roulers",
    province: "Flandre-Occidentale",
    workerBand: "20-49",
    sector: "Horticulture",
    scenario: "ok",
    healthScore: 62,
    healthBand: "Solide",
    whyCallNow:
      "Saison des plantations + contrat avec 3 nouvelles communes — pic de 15 saisonniers à gérer dès septembre.",
    signals: [
      { date: "23 juil. 2026", title: "Marchés d'entretien remportés dans 3 communes flamandes", source: "Krant van West-Vlaanderen" },
      { date: "6 juil. 2026", title: "Appel à 15 ouvriers saisonniers pour la saison de plantation", source: "Site web" },
    ],
    contacts: [
      { name: "Wim Van Damme", role: "Zaakvoerder", roleGroup: "CEO", email: "w.vandamme@vandamme-groen.example" },
      { name: "Sofie Declerck", role: "Boekhouding", roleGroup: "Comptabilité", email: "s.declerck@vandamme-groen.example" },
      { name: "Lore Vanhee", role: "Personeelszaken", roleGroup: "RH", email: "l.vanhee@vandamme-groen.example" },
    ],
    otherContactsCount: 9,
  },
];
